#set($thingName = ${context.arguments.thingName})
#set($startTimestamp = $util.time.nowEpochMilliSeconds()-${context.arguments.timeAgoInSecs}*1000)
#set($ThingNameAndMetric = "${thingName}-${context.arguments.metricName}")
{
    "version" : "2017-02-28",
    "operation" : "Query",
    "query" : {
        "expression" : "ThingNameAndMetric = :ThingNameAndMetric AND #t >= :startTimestamp",
        "expressionValues" : {
            ":ThingNameAndMetric": {"S": "${ThingNameAndMetric}"},
            ":startTimestamp": {"N": $startTimestamp}
        },
        "expressionNames": {
            "#t": "Timestamp"
        }
    }
}
