AWSTemplateFormatVersion: 2010-09-09
Description: Helper CloudFormation to create a static webiste S3 Bucket dev pipeline
Parameters:
  BucketName:
    Type: String
    Description: >-
      The name for the bucket that will host a version of your website, e.g.
      'your-website-bucket'
  GitHubOwner:
    Description: GitHub account username.
    Type: String
  GitHubRepo:
    Description: Static site repo name.
    Type: String
  GitHubProdBranch:
    Description: The branch that will trigger build/deploy.
    Type: String
    Default: master
  GitHubStagingBranch:
    Description: The branch that will trigger build/deploy.
    Type: String
    Default: develop
  GitHubOAuthToken:
    Description: OAuth or personal access token.
    Type: String
    NoEcho: true
  ErrorDocument:
    Description: Custom error document for the static website.
    Type: String
    Default: 404.html

Resources:

  # S3 - Prod

  StaticSiteBucketProd:
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: !Ref ErrorDocument
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain

  StaticSiteBucketProdPolicy:
    Properties:
      Bucket: !Ref StaticSiteBucketProd
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${StaticSiteBucketProd}/*'
    Type: 'AWS::S3::BucketPolicy'

  # End S3 - Prod

  # S3 - Staging

  StaticSiteBucketStaging:
    Properties:
      BucketName: !Join [ "-", [ !Ref BucketName, staging ] ]
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: !Ref ErrorDocument
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain

  StaticSiteBucketStagingPolicy:
    Properties:
      Bucket: !Ref StaticSiteBucketStaging
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${StaticSiteBucketStaging}/*'
    Type: 'AWS::S3::BucketPolicy'

  # End S3 - Staging

  # S3 - Artifacts

  ArtifactBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      AccessControl: Private

  # End S3 - Artifacts

  # Codepipeline

  CodeBuildRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
  
  CodeBuildRolePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: CodeBuildRolePolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Resource:
              - !Sub >-
                arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*
            Action:
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
          - Effect: Allow
            Resource:
              - !Sub 'arn:aws:s3:::${ArtifactBucket}'
              - !Sub 'arn:aws:s3:::${ArtifactBucket}/*'
              - !Sub 'arn:aws:s3:::${StaticSiteBucketProd}'
              - !Sub 'arn:aws:s3:::${StaticSiteBucketProd}/*'
              - !Sub 'arn:aws:s3:::${StaticSiteBucketStaging}'
              - !Sub 'arn:aws:s3:::${StaticSiteBucketStaging}/*'
            Action:
              - 's3:*'
      Roles:
        - !Ref CodeBuildRole

  CodeBuildProd:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/ubuntu-base:14.04'
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: BUCKET_NAME
            Value: !Ref StaticSiteBucketProd
      Name: !Sub '${AWS::StackName}-StaticSiteBuilder-Prod'
      ServiceRole: !Ref CodeBuildRole
      Source:
        Type: CODEPIPELINE
      Tags:
        - Key: Stack
          Value: !Ref 'AWS::StackName'
      TimeoutInMinutes: 10

  CodeBuildStaging:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/ubuntu-base:14.04'
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: BUCKET_NAME
            Value: !Ref StaticSiteBucketStaging
      Name: !Sub '${AWS::StackName}-StaticSiteBuilder-Staging'
      ServiceRole: !Ref CodeBuildRole
      Source:
        Type: CODEPIPELINE
      Tags:
        - Key: Stack
          Value: !Ref 'AWS::StackName'
      TimeoutInMinutes: 10

  CodePipelineRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /

  CodePipelineRolePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: CodePipelineRolePolicy
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
              - 's3:GetObjectVersion'
              - 's3:GetBucketVersioning'
            Resource: '*'
            Effect: Allow
          - Action:
              - 's3:PutObject'
            Resource:
              - !Sub 'arn:aws:s3:::${ArtifactBucket}'
              - !Sub 'arn:aws:s3:::${ArtifactBucket}/*'
            Effect: Allow
          - Action:
              - 'codebuild:BatchGetBuilds'
              - 'codebuild:StartBuild'
            Resource: '*'
            Effect: Allow
      Roles:
        - !Ref CodePipelineRole

  CodePipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      RoleArn: !GetAtt 
        - CodePipelineRole
        - Arn
      Stages:
        - Name: Source
          Actions:
            - Name: SourceActionProd
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: '1'
                Provider: GitHub
              OutputArtifacts:
                - Name: StaticSiteSourceProd
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubProdBranch
                OAuthToken: !Ref GitHubOAuthToken
              RunOrder: 1
            - Name: SourceActionStaging
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: '1'
                Provider: GitHub
              OutputArtifacts:
                - Name: StaticSiteSourceStaging
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubStagingBranch
                OAuthToken: !Ref GitHubOAuthToken
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: CodeBuildProd
              InputArtifacts:
                - Name: StaticSiteSourceProd
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              OutputArtifacts:
                - Name: StaticSiteProd
              Configuration:
                ProjectName: !Ref CodeBuildProd
              RunOrder: 1
            - Name: CodeBuildStaging
              InputArtifacts:
                - Name: StaticSiteSourceStaging
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              OutputArtifacts:
                - Name: StaticSiteStaging
              Configuration:
                ProjectName: !Ref CodeBuildStaging
              RunOrder: 1
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket

  # End - Codepipeline

Outputs:
  WebsiteURL:
    Value: !GetAtt 
      - StaticSiteBucketProd
      - WebsiteURL
