{
    "version" : "2017-02-28",
    "operation" : "Invoke",
    "payload": {
        "cmd": "addDevice",
        "name": "$context.arguments.name",
        "deviceTypeId": "$context.arguments.deviceTypeId",
        "deviceBlueprintId": "$context.arguments.deviceBlueprintId"
    }
}
