{
    "version" : "2017-02-28",
    "operation" : "Invoke",
    "payload": {
        "cmd": "updateDevice",
        "thingId": "$context.arguments.thingId",
        "name": "$context.arguments.name",
        "spec": "$context.arguments.spec",
        "deviceTypeId": "$context.arguments.deviceTypeId",
        "deviceBlueprintId": "$context.arguments.deviceBlueprintId"
    }
}
