{
    "version" : "2017-02-28",
    "operation" : "Invoke",
    "payload": {
        "cmd": "addSolution",
        "name": "$context.arguments.name",
        "description": "$context.arguments.description",
        "thingIds": "$context.arguments.thingIds",
        "solutionBlueprintId": "$context.arguments.solutionBlueprintId"
    }
}
