{
    "version" : "2017-02-28",
    "operation" : "Invoke",
    "payload": {
        "cmd": "listUsers"
        #if( ${context.arguments.limit} )
            ,
            "limit": ${context.arguments.limit}
        #end
        #if( ${context.arguments.paginationToken} )
            ,
            "paginationToken": "${context.arguments.paginationToken}"
        #end
    }
}
