{
    "version" : "2017-02-28",
    "operation" : "Invoke",
    "payload": {
        "cmd": "inviteUser",
        "name": "${context.arguments.name}",
        "email": "${context.arguments.email}",
        "groups": ${context.arguments.groups}
    }
}
