#set( $expression = "SET #t = :t, #uA = :uA" )
{
    "version" : "2017-02-28",
    "operation" : "UpdateItem",
    "key" : {
        "id" : $util.dynamodb.toStringJson($ctx.args.id)
    },
    "update" : {
        "expressionValues": {
            #if( $ctx.args.setting )
                #set( $expression = "$expression, setting = :setting" )
                ":setting": $util.dynamodb.toMapJson($ctx.args.setting),
            #end
            ":t" : $util.dynamodb.toStringJson($ctx.args.type),
            ":uA" : $util.dynamodb.toStringJson($util.time.nowISO8601())
        },
        "expression" : "$expression",
        "expressionNames": {
            "#t": "type",
            "#uA": "updatedAt"
        }
    }
}
