#set( $expression = "SET #n = :n, #d = :d, #uA = :uA" )
{
    "version" : "2017-02-28",
    "operation" : "UpdateItem",
    "key" : {
        "id" : $util.dynamodb.toStringJson($ctx.args.id)
    },
    "update" : {
        "expressionValues": {
            #if( $ctx.args.spec )
                ## Add spec to expression
                #set( $expression = "$expression, spec = :spec" )
                ":spec" :$util.dynamodb.toMapJson($ctx.args.spec),
            #end
            ":n" : $util.dynamodb.toStringJson($ctx.args.name),
            ":d" : $util.dynamodb.toStringJson($ctx.args.description),
            ":uA" : $util.dynamodb.toStringJson($util.time.nowISO8601())
        },
        "expression" : "$expression",
        "expressionNames": {
            "#n": "name",
            "#d": "description",
            "#uA": "updatedAt"
        }
    }
}
